    1. 텐서 플로우 1.x : snowdeer_env
    2. 텐서 플로우 2.x : keras_study

## <b>■ 복습</b>
    1장. Numpy
    2장. 퍼셉트론
    3장. 3층 신경망 구현
    4장. 2층 신경망 구현(수치미분)
    5장. 2층 신경망 구현(오차 역전파)
    6장. 신경망 학습 기술들
        - under-fitting 방지
        - over-fitting 방지
    7장. CNN을 이용한 3층 신경망 구현
    ------------------------------------------2010년
    8장. 딥러닝 역사 
        1. 텐서 플로우
        2. Object detection (자율 주행차, 불량품 선별, 종양 발견 등)
        3. RNN (주가 예측, 번역 신경망, 작곡 등)

### <b>■ 텐서 플로우 1.x버전의 큰 그림</b>
    딥러닝 면접질문 : 딥러닝 프레임워크는 뭘 썼는가?
        1. 텐서 플로우 1.x, 2.x 사용
        2. Pytorch 사용
        
    다차원 데이터가 흘러가는 그래프를 구성하는 부분
    -------------------------------------------
    다차원 데이터가 흘러가는 그래프를 실행하는 부분

#### 예제1. 문자열 데이터 출력

In [2]:
import tensorflow as tf
hello = tf.constant("Hello Tensorflow")

sess = tf.Session() # 그래프를 실행할 세션을 구성

print(sess.run(hello))

C:\Users\knitwill\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\knitwill\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\knitwill\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\knitwill\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWa

b'Hello Tensorflow'


    파이썬 3버전은 문자열 unicode가 기본이므로
    str을 이용해서 encoding 처리를 해주면서 binary 타입을 unicode 타입으로 반환해줘야 함

In [3]:
print(str(sess.run(hello),encoding='utf-8'))

Hello Tensorflow


#### 예제2. 숫자형 변수를 출력

In [4]:
################################################ 그래프 그리는 영역
import tensorflow as tf
x = tf.constant(35, name='x') # x라는 상수값을 만들고 숫자 35를 지정
y = tf.Variable(x+5, name='y') # y라는 변수를 만들고 방정식 x+5를 정의
model = tf.global_variables_initializer() # 변수를 생성했으면 초기화 해줘야하는데 필요한 명령어. 무조건 초기화를 해줘야 실행 가능

################################################ 그래프 실행할 영역
sess = tf.Session()
sess.run(model)

Instructions for updating:
Colocations handled automatically by placer.


#### 예제3. 상수형 변수를 실행하기

In [5]:
import tensorflow as tf
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add_1:0", shape=(), dtype=int32)


### ※ 문제110. 위에서 만든 텐서 그래프를 실행하시오

In [8]:
import tensorflow as tf
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)

sess = tf.Session()
print(sess.run(c))

sess.close() # 세션을 닫는 구문을 작성해줘야 함

42


In [9]:
# 다른 방법으로 세션 종료
import tensorflow as tf
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)

with tf.Session() as sess:
    print(sess.run(c))
# 위와 같이 with절을 이용하면 close를 안해도 자동으로 닫힌다.

42


### ※ 문제11. 아래의 그래프를 실행하시오

In [11]:
import tensorflow as tf
old_v = tf.logging.get_verbosity()
tf.logging.set_verbosity(tf.logging.ERROR)

a = tf.add(1, 2)
b = tf.multiply(a, 3)
c = tf.add(b, 5)
d = tf.multiply(c, 6)
e = tf.multiply(d, 5)
f = tf.div(e, 6)
g = tf.add(f, d)
h = tf.multiply(g, f)

with tf.Session() as sess:
    print(sess.run(h))

10780


#### 예제4. 텐서플로우로 loop문 실행
    1부터 5까지 숫자를 출력

In [12]:
# 파이썬 기본 문법으로 수행
for i in range(1,6):
    print(i)

1
2
3
4
5


In [13]:
# 텐서 플로우로 수행
import tensorflow as tf
x = tf.Variable(0)
init = tf.global_variables_initializer() # 변수를 생성했으면 초기화를 해줘야 함

with tf.Session() as sess :
    sess.run(init)
    for i in range(5):
        x = x+1
        print(sess.run(x))

1
2
3
4
5


### ※ 문제112. 위의 코드를 이용해서 구구단 2단을 출력하시오
    (tf.multiply를 이용)

In [21]:
import tensorflow as tf
with tf.Session() as sess:
    for i in range(1,10):        
        m = tf.multiply(2,i)
        print(f'2 x {i} = {sess.run(m)}')

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18


### ※ 문제113. 구구단 2단 ~ 9단까지 출력하시오

In [24]:
import tensorflow as tf
with tf.Session() as sess:
    for i in range(2,10):
        for j in range(1,10):
            print(f"{i} x {j} = {sess.run(tf.multiply(i,j))}")

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [25]:
x = tf.Variable(0)
y = tf.Variable(0)
z = tf.multiply(x, y)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    for i in range(2,10):
        for j in range(1,10):
            print(i, 'x', j, '=', sess.run(z, feed_dict=({x:i, y:j})))

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


    feed_dict 명령어로 데이터를 텐서 그래프에 주입
        x 변수에는 i의 값을 대입, y 변수에는 j 값을 대입
        z를 실행하기 위해서 x와 y에 값을 대입

### <b>■ 신경망에서 bias를 만드는 코드를 텐서 플로우로 구현하는 방법</b>
#### 예제1. 변수에 숫자 0과 숫자 1을 채워 넣는 배열을 생성하는 방법    

In [26]:
print('numpy 구현')
import numpy as np
a = np.zeros((2,2))
b = np.ones((2,2))
print(a)
print(b)

print('\n tensorflow 구현')
a = tf.zeros((2,2))
b = tf.ones((2,2))
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(a))
    print(sess.run(b))

numpy 구현
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]

 tensorflow 구현
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


### <b>■ 배열의 원소중에서 최댓값 원소의 인덱스를 찾는 코드</b>

In [28]:
print('파이썬의 numpy 이용방법')
import numpy as np
a = np.array([0,0,1,0,0,0,0,0,0,0])
print(np.argmax(a, axis=0))

print('\n 텐서플로우 이용방법')
import tensorflow as tf
a = np.array([0,0,1,0,0,0,0,0,0,0])
b = tf.argmax(a, axis=0)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))

파이썬의 numpy 이용방법
2

 텐서플로우 이용방법
2


### ※ 문제11. 아래의 원핫 인코딩된 배열에서 최대 원소값의 인덱스를 출력하시오

In [30]:
import numpy as np
a = np.array([[0,0,1,0,0,0,0,0,0,0],
              [0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,1,0,0,0],
              [1,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0]])
import tensorflow as tf
b = tf.argmax(a, axis=1)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))

[2 4 6 0 8]


### <b>■ 다차원 배열에서의 행의 토탈값 구하는 방법</b>


In [32]:
import numpy as np
a = np.array([[[1, 2, 3],
               [2, 1, 4],
               [5, 2, 1],
               [6, 3, 2]],
              [[5, 1, 3],
               [1, 3, 4],
               [4, 2, 6],
               [3, 9, 3]],
              [[4, 5, 6],
               [7, 4, 3],
               [2, 1, 5],
               [4, 3, 1]]])

print('numpy 이용했을 때')
print(np.sum(a, axis=0))

print('\n 텐서 플로우 이용했을 때')
a = np.array([[[1, 2, 3],
               [2, 1, 4],
               [5, 2, 1],
               [6, 3, 2]],
              [[5, 1, 3],
               [1, 3, 4],
               [4, 2, 6],
               [3, 9, 3]],
              [[4, 5, 6],
               [7, 4, 3],
               [2, 1, 5],
               [4, 3, 1]]])
import tensorflow as tf
d = tf.reduce_sum(a, reduction_indices=[0])

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(d))

numpy 이용했을 때
[[10  8 12]
 [10  8 11]
 [11  5 12]
 [13 15  6]]

 텐서 플로우 이용했을 때
[[10  8 12]
 [10  8 11]
 [11  5 12]
 [13 15  6]]


### ※ 문제115. 위에는 3차원 데이터의 축의 값을 토탈값을 구했는데 평균값을 구하는걸로 출력해보시오

In [33]:
a = np.array([[[1, 2, 3],
               [2, 1, 4],
               [5, 2, 1],
               [6, 3, 2]],
              [[5, 1, 3],
               [1, 3, 4],
               [4, 2, 6],
               [3, 9, 3]],
              [[4, 5, 6],
               [7, 4, 3],
               [2, 1, 5],
               [4, 3, 1]]])
import tensorflow as tf
d = tf.reduce_mean(a, reduction_indices=[0])

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(d))

[[3 2 4]
 [3 2 3]
 [3 1 4]
 [4 5 2]]


### <b>■ 텐서 플로우로 행렬 내적하는 코드</b>

In [35]:
print('numpy 형식')
a = np.array([[2,2,2],[2,2,2]])
b = np.array([[3,3],[3,3],[3,3]])
res = np.dot(a,b)
print(res)

print('\n tensorflow 형식')
x = tf.placeholder("float",[2,3]) # (2,3) 행렬의 실수형 데이터를 담을 변수
y = tf.placeholder("float",[3,2]) 
rs = tf.matmul(x, y)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(rs, feed_dict={x:[[2,2,2],[2,2,2]], y:[[3,3],[3,3],[3,3]]}))

numpy 형식
[[18 18]
 [18 18]]

 tensorflow 형식
[[18. 18.]
 [18. 18.]]


### ※ 문제116. (점심시간 문제) 아래의 행렬의 내적을 텐서플로우로 구현하시오
$$\begin{pmatrix} 6 & 7 \\ 3 & 5 \\ 2 & 9 \\ \end{pmatrix} \cdot \begin{pmatrix} 3 & 8 & 1 \\ 4 & 5 & 2 \\ \end{pmatrix}$$

In [38]:
a = np.array([[6,7],[3,5],[2,9]])
b = np.array([[3,8,1],[4,5,2]])

import tensorflow as tf
x = tf.placeholder("float",[3,2]) # (2,3) 행렬의 실수형 데이터를 담을 변수
y = tf.placeholder("float",[2,3]) 
rs = tf.matmul(x, y)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(rs, feed_dict={x:[[6,7],[3,5],[2,9]], y:[[3,8,1],[4,5,2]]}))

[[46. 83. 20.]
 [29. 49. 13.]
 [42. 61. 20.]]


### <b>■ 신경망의 정확도를 출력하는 코드를 이해</b>
    tensorflow의 cast 함수의 이해
#### 예제1: 아래의 배열의 True를 1로 변경하고 False를 0으로 변경

In [41]:
import tensorflow as tf

correct_prediction = [ True, False , True  ,True  ,True  ,True  ,True,  True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True, False , True  ,True, False , True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True ,False , True  ,True  ,True  ,True  ,True
  ,True  ,True, False , True, False , True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
 ,False , True  ,True  ,True]

sess = tf.Session()

a = tf.cast(correct_prediction, 'float')
print(sess.run(a))
sess.close()

[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 1. 1. 1.]


#### 예제2. 위의 출력된 결과에서 전체 개수 중에 1이 몇개나 되는지 확인하여 정확도가 아래와 같이 출력되게 하시오
    결과: 0.93
    전부 다 더해서 전체 개수로 나눈 값을 출력

In [42]:
sess = tf.Session()

a = tf.cast(correct_prediction, 'float')
b = tf.reduce_mean(a)
print(sess.run(b))
sess.close()

0.93


### <b>■ 텐서 플로우에서 mnist 데이터 가져오기</b>
    텐서 플로우는 기본적으로 실습용으로 mnist 데이터가 내장되어 있다.

In [48]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

batch_xs, batch_ys = mnist.train.next_batch(100) # 100개의 데이터만 가져오기

print(batch_xs.shape)
print(batch_ys.shape)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)
(100, 10)


### ※ 문제117. mnist데이터에서 test 데이터 100개를 불러오시오

In [49]:
batch_xs, batch_ys = mnist.test.next_batch(100)

print(batch_xs.shape)
print(batch_ys.shape)

(100, 784)
(100, 10)


### <b>■ 텐서 플로우에서 배치단위로 데이터를 불러올 때 None의 의미</b>
#### 예제1. 아래의 숫자 2로 채워진 행렬 (2,3) 행렬을 텐서 플로우로 작성

In [55]:
import tensorflow as tf
x = tf.placeholder("float",[2,3])
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(x, feed_dict={x:[[2,2,2],[2,2,2]]}))
sess.close()

[[2. 2. 2.]
 [2. 2. 2.]]


#### 예제2. 위의 코드에서 [2,3] --> [None, 3] 으로 변경해서 실행하시오

In [57]:
import tensorflow as tf
x = tf.placeholder("float",[None,3]) # None으로 작성 -> 행의 개수 무관하게 작성 가능

sess = tf.Session()
init = tf.global_variables_initializer()

sess.run(init)
print(sess.run(x, feed_dict={x:[[2,2,2],[2,2,2],[2,2,2]]}))

sess.close()

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### ※ 문제118. mnist 데이터 784(28x28)개에 맞게 x 변수를 placeholder로 선언하고 배치로 입력될 데이터의 건수는 몇개든 관계없이 None을 사용한 변수를 만들고 mnist 데이터를 x변수에 100개를 담고 출력

In [60]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder('float',[None,784])

batch_xs, batch_ys = mnist.train.next_batch(100)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x, feed_dict={x:batch_xs}).shape)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)


### <b>■ 텐서 플로우로 신경망을 만들 때 가중치를 생성하는 코드</b>

In [63]:
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) # [-1,1] 사이의 숫자로 (784,50) 행렬의 변수를 W1로 생성
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(W1).shape)

(784, 50)


### ※ 문제119. mnist의 훈련 데이터 (100,784)와 가중치 행렬 W1 (784,50)과 행렬곱(내적)한 결과를 출력하시오

In [65]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder('float',[None,784])
# 앞으로 행렬로 어떤 데이터를 feed_dict 할거라 placeholder로 생성
batch_xs, batch_ys = mnist.train.next_batch(100)
    
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) 
rs = tf.matmul(x, W1)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(rs, feed_dict={x:batch_xs}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[ -6.606185     3.0263307    1.0772773  ...  -9.260778    -0.5921345
    2.9072022 ]
 [ -3.9356213   16.533857    -0.6530335  ...  -7.138557     1.1199387
   -2.3136544 ]
 [ -4.938776    10.810218    -0.09185028 ... -11.143063    -8.253414
    4.3693542 ]
 ...
 [ -2.5267358   10.737777     0.44050515 ...  -5.3788486   -1.6410785
    2.015374  ]
 [ -2.5639768    0.7654307    1.4454873  ...  -5.053457    -1.6340002
    5.377161  ]
 [ -7.069396     6.8005834   -1.6288438  ...  -6.4135303   -1.8623493
    4.1806006 ]]


### ※ 문제120. (1,50) bias 생성하는데 변수를 b로 해서 생성하고 숫자1로 다 채우시오

In [69]:
b = tf.Variable(tf.ones([1,50]))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    print(sess.run(b).shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]
(1, 50)


### ※ 문제121. mnist 훈련 데이터 100개와 W1 (784, 50)으로 만든 가중치와 내적한 결과와 위의 bias의 합을 구하시오

In [74]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder('float',[None,784])
# 앞으로 행렬로 어떤 데이터를 feed_dict 할거라 placeholder로 생성
batch_xs, batch_ys = mnist.train.next_batch(100)
    
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) 
b = tf.Variable(tf.ones([1,50]))
rs = tf.matmul(x, W1) + b

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(rs, feed_dict={x:batch_xs}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[ 6.238037    8.98834    11.626779   ...  7.19136    -1.9642506
  -6.152054  ]
 [ 4.2653418   5.134612    6.7903295  ...  4.772041   -1.7245097
   3.3326375 ]
 [ 2.9617202  -1.1303968   2.6033964  ...  1.8364942   3.7090244
   0.39990473]
 ...
 [ 0.6526172   2.88939    10.071863   ...  8.315824   -0.4677856
  -3.9605932 ]
 [ 1.7657442   9.639545    8.359711   ...  4.585883    3.3009493
   1.2603588 ]
 [-1.3883157   1.3874772   9.155603   ... -2.3095734   4.9295473
   1.3065573 ]]


### ※ 문제122. 위의 내적한 결과 y를 시그모이드 함수에 통과시켜서 y_hat으로 출력하시오

In [75]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder('float',[None,784])
# 앞으로 행렬로 어떤 데이터를 feed_dict 할거라 placeholder로 생성
batch_xs, batch_ys = mnist.train.next_batch(100)
    
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) 
b = tf.Variable(tf.ones([1,50]))
rs = tf.matmul(x, W1) + b

y_hat = tf.sigmoid(rs)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y_hat, feed_dict={x:batch_xs}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[2.92897224e-04 1.00224525e-01 9.99111474e-01 ... 8.86635482e-01
  8.12573910e-01 8.97140622e-01]
 [6.86297715e-02 2.03251839e-03 9.84430432e-01 ... 8.38124990e-01
  2.82424688e-03 9.71738935e-01]
 [4.23902810e-01 2.13101506e-03 9.88733530e-01 ... 6.20792031e-01
  3.66568565e-06 1.27492547e-02]
 ...
 [3.98921967e-03 9.90533590e-01 9.37338769e-02 ... 9.70375419e-01
  2.68167853e-01 9.89655375e-01]
 [7.01248646e-05 1.39116943e-02 9.99566078e-01 ... 4.85259742e-01
  1.61417007e-01 6.35398805e-01]
 [1.67247653e-03 6.00573421e-03 8.56327295e-01 ... 7.68782377e-01
  4.18158472e-02 9.99859214e-01]]


### ※ 문제123. 위의 활성화 함수를 sigmoid에서 relu로 변경하시오

In [77]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder('float',[None,784])
# 앞으로 행렬로 어떤 데이터를 feed_dict 할거라 placeholder로 생성
batch_xs, batch_ys = mnist.train.next_batch(100)
    
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) 
b = tf.Variable(tf.ones([1,50]))
rs = tf.matmul(x, W1) + b

y_hat = tf.nn.relu(rs)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y_hat, feed_dict={x:batch_xs}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[ 5.404805    0.         12.500315   ...  0.          0.86951053
   0.        ]
 [ 1.4221957   4.131101    6.9718895  ...  0.          2.6015842
   0.77431184]
 [ 7.3012156   0.          6.3533626  ...  5.0717263   0.
   0.        ]
 ...
 [ 7.2641616   0.          7.71401    ...  4.5675993   0.78730726
   0.27933908]
 [ 1.5166872   0.          4.178323   ...  7.192248    2.5692124
   4.812578  ]
 [ 3.3317857   0.          0.         ...  5.887022    2.6854236
   0.        ]]


### ※ 문제124. 위의 1층 신경망을 통과한 y_hat (100,50)과 (50,10) 으로 만든 W2와의 내적한 결과가 z로 출력되게끔 출력층 코드를 추가하시오

In [80]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
batch_xs, batch_ys = mnist.train.next_batch(100)

# 은닉1층
x = tf.placeholder('float',[None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1)) 
b1 = tf.Variable(tf.ones([1,50]))
y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y)

# 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([1,10]))
z = tf.matmul(y_hat,W2) + b2

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(z, feed_dict={x:batch_xs}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[-7.10862541e+00 -1.53333855e+01 -2.22393837e+01 -4.15927124e+01
  -1.03115921e+01 -6.56896973e+00 -1.08590374e+01 -2.75789661e+01
   1.35529690e+01  2.52315006e+01]
 [ 1.93139935e+00 -3.67275543e+01 -6.22521544e+00 -5.47236481e+01
  -2.01815300e+01  2.21018829e+01 -1.12713604e+01 -3.48640785e+01
   8.22161388e+00  2.92435684e+01]
 [-9.25604725e+00 -1.00887604e+01  1.89971066e+01 -2.34644184e+01
   7.93770885e+00  5.18727922e+00 -7.84276009e-01 -1.10859919e+01
  -1.38790112e+01  4.60087013e+00]
 [ 2.81498194e+00 -1.63552094e+01  2.47417974e+00 -3.61777229e+01
  -1.18232126e+01  3.43369865e+01 -1.49229565e+01 -3.42680588e+01
  -1.74873695e+01  1.80363503e+01]
 [-1.87543297e+01 -2.07667007e+01 -8.45582008e+00 -1.53031349e+01
   1.12859213e+00  8.82600975e+00 -1.56886959e+01 -9.01890945e+00
  -2.0